export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUESTS = 'LOGIN_REQUESTS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_REQUESTS = 'REGISTER_USER_REQUESTS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_REQUESTS = 'LOAD_USER_REQUESTS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
